@ProductManagement.API_HostAddress = http://localhost:5068

Post {{ProductManagement.API_HostAddress}}/api/Invoice
Content-Type: application/json
Accept: application/json
{
  "customerId": 3,
  "items": [
    { "productId": 1002, "quantity": 3 },
    { "productId": 1003, "quantity": 2}
  ]
}




